spring:
  data:
    mongodb:
      database: CommandsInfo
      host: 172.17.0.2
      port: 27017
      auto-index-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080
  error:
    include-message: always
